// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVZR2n2cvcp8AFBYe6PVfnNSh1ynUjrYM',
    appId: '1:1084114580182:web:443a32e380558b0058cf77',
    messagingSenderId: '1084114580182',
    projectId: 'ezpc-tasks',
    authDomain: 'ezpc-tasks.firebaseapp.com',
    storageBucket: 'ezpc-tasks.appspot.com',
    measurementId: 'G-R581KRBBP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlBi2jSvSgwk7xFi3mEf3HKDgIWRVlXhA',
    appId: '1:1084114580182:android:293533fe6348d48758cf77',
    messagingSenderId: '1084114580182',
    projectId: 'ezpc-tasks',
    storageBucket: 'ezpc-tasks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBLbiqPE1NVr84BhNOze4rYeo_UoAbTNE',
    appId: '1:1084114580182:ios:00c4a586163a774f58cf77',
    messagingSenderId: '1084114580182',
    projectId: 'ezpc-tasks',
    storageBucket: 'ezpc-tasks.appspot.com',
    iosBundleId: 'com.example.ezpcTasksApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBLbiqPE1NVr84BhNOze4rYeo_UoAbTNE',
    appId: '1:1084114580182:ios:00c4a586163a774f58cf77',
    messagingSenderId: '1084114580182',
    projectId: 'ezpc-tasks',
    storageBucket: 'ezpc-tasks.appspot.com',
    iosBundleId: 'com.example.ezpcTasksApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVZR2n2cvcp8AFBYe6PVfnNSh1ynUjrYM',
    appId: '1:1084114580182:web:b398751c6727075558cf77',
    messagingSenderId: '1084114580182',
    projectId: 'ezpc-tasks',
    authDomain: 'ezpc-tasks.firebaseapp.com',
    storageBucket: 'ezpc-tasks.appspot.com',
    measurementId: 'G-6VSYMFYXGB',
  );
}
